package com.myspace.fg_rules;
/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Features implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("featureId")
	private int featureId;

	@org.kie.api.definition.type.Label("Feature Name")
	private java.lang.String featureName;

	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Feature Epic")
	private java.util.List<java.lang.String> featureEpic;

	@org.kie.api.definition.type.Label("Feature Description")
	private java.lang.String featureDesc;

	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("Feature Component")
	private java.util.List<java.lang.String> featureComponent;

	@org.kie.api.definition.type.Label("Feature Major Version")
	private java.lang.String featureMajorVer;

	@org.kie.api.definition.type.Label("Feature Minor Version")
	private java.lang.String featureMinorVer;

	@org.kie.api.definition.type.Label(value = "Enabled")
	private java.lang.Boolean isEnabled;

	public Features() {
	}

	public int getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(int featureId) {
		this.featureId = featureId;
	}

	public java.lang.String getFeatureName() {
		return this.featureName;
	}

	public void setFeatureName(java.lang.String featureName) {
		this.featureName = featureName;
	}

	public java.util.List<java.lang.String> getFeatureEpic() {
		return this.featureEpic;
	}

	public void setFeatureEpic(java.util.List<java.lang.String> featureEpic) {
		this.featureEpic = featureEpic;
	}

	public java.lang.String getFeatureDesc() {
		return this.featureDesc;
	}

	public void setFeatureDesc(java.lang.String featureDesc) {
		this.featureDesc = featureDesc;
	}

	public java.util.List<java.lang.String> getFeatureComponent() {
		return this.featureComponent;
	}

	public void setFeatureComponent(
			java.util.List<java.lang.String> featureComponent) {
		this.featureComponent = featureComponent;
	}

	public java.lang.String getFeatureMajorVer() {
		return this.featureMajorVer;
	}

	public void setFeatureMajorVer(java.lang.String featureMajorVer) {
		this.featureMajorVer = featureMajorVer;
	}

	public java.lang.String getFeatureMinorVer() {
		return this.featureMinorVer;
	}

	public void setFeatureMinorVer(java.lang.String featureMinorVer) {
		this.featureMinorVer = featureMinorVer;
	}

	public java.lang.Boolean getIsEnabled() {
		return this.isEnabled;
	}

	public void setIsEnabled(java.lang.Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	public Features(int featureId, java.lang.String featureName,
			java.util.List<java.lang.String> featureEpic,
			java.lang.String featureDesc,
			java.util.List<java.lang.String> featureComponent,
			java.lang.String featureMajorVer, java.lang.String featureMinorVer,
			java.lang.Boolean isEnabled) {
		this.featureId = featureId;
		this.featureName = featureName;
		this.featureEpic = featureEpic;
		this.featureDesc = featureDesc;
		this.featureComponent = featureComponent;
		this.featureMajorVer = featureMajorVer;
		this.featureMinorVer = featureMinorVer;
		this.isEnabled = isEnabled;
	}

}
