package com.myspace.mdp_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class StrategyParameters implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "STRATEGYPARAMETERS_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "STRATEGYPARAMETERS_ID_SEQ", name = "STRATEGYPARAMETERS_ID_GENERATOR")
    private java.lang.Long id;

    public StrategyParameters() {
    }
    
    public StrategyParameters(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}